apiVersion: v1
kind: Service
metadata:
  name: canary-stable
spec:
  selector:
    app: canary
    version: v1   # currently stable version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
